package com.rodrigoguerrero.theme.colors

import android.annotation.SuppressLint
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

internal val dark_primary = Color(0xFF3DDAE7)
internal val dark_onPrimary = Color(0xFF00363B)
internal val dark_primaryContainer = Color(0xFF004F55)
internal val dark_onPrimaryContainer = Color(0xFF80F4FF)
internal val dark_secondary = Color(0xFFB1CBCE)
internal val dark_onSecondary = Color(0xFF1B3437)
internal val dark_secondaryContainer = Color(0xFF324B4D)
internal val dark_onSecondaryContainer = Color(0xFFCCE8EA)
internal val dark_tertiary = Color(0xFFB7C7EA)
internal val dark_onTertiary = Color(0xFF21304C)
internal val dark_tertiaryContainer = Color(0xFF384764)
internal val dark_onTertiaryContainer = Color(0xFFD7E2FF)
internal val dark_error = Color(0xFFFFB4AB)
internal val dark_errorContainer = Color(0xFF93000A)
internal val dark_onError = Color(0xFF690005)
internal val dark_onErrorContainer = Color(0xFFFFDAD6)
internal val dark_background = Color(0xFF000000)
internal val dark_onBackground = Color(0xFFE0E3E3)
internal val dark_surface = Color(0xFF191C1D)
internal val dark_onSurface = Color(0xFFE0E3E3)
internal val dark_surfaceVariant = Color(0xFF3F4849)
internal val dark_onSurfaceVariant = Color(0xFFBEC8C9)
internal val dark_outline = Color(0xFF899393)
internal val dark_inverseOnSurface = Color(0xFF191C1D)
internal val dark_inverseSurface = Color(0xFFE0E3E3)
internal val dark_inversePrimary = Color(0xFF006970)
internal val dark_shadow = Color(0xFF000000)
internal val dark_surfaceTint = Color(0xFF3DDAE7)
internal val dark_outlineVariant = Color(0xFF3F4849)
internal val dark_scrim = Color(0xFF000000)

internal val light_primary = Color(0xFF006970)
internal val light_onPrimary = Color(0xFFFFFFFF)
internal val light_primaryContainer = Color(0xFF80F4FF)
internal val light_onPrimaryContainer = Color(0xFF002022)
internal val light_secondary = Color(0xFF4A6365)
internal val light_onSecondary = Color(0xFFFFFFFF)
internal val light_secondaryContainer = Color(0xFFCCE8EA)
internal val light_onSecondaryContainer = Color(0xFF051F22)
internal val light_tertiary = Color(0xFF505E7D)
internal val light_onTertiary = Color(0xFFFFFFFF)
internal val light_tertiaryContainer = Color(0xFFD7E2FF)
internal val light_onTertiaryContainer = Color(0xFF0B1B36)
internal val light_error = Color(0xFFBA1A1A)
internal val light_errorContainer = Color(0xFFFFDAD6)
internal val light_onError = Color(0xFFFFFFFF)
internal val light_onErrorContainer = Color(0xFF410002)
internal val light_background = Color(0xFFFAFDFD)
internal val light_onBackground = Color(0xFF191C1D)
internal val light_surface = Color(0xFFFAFDFD)
internal val light_onSurface = Color(0xFF191C1D)
internal val light_surfaceVariant = Color(0xFFFAFDFD)
internal val light_onSurfaceVariant = Color(0xFF3F4849)
internal val light_outline = Color(0xFF6F797A)
internal val light_inverseOnSurface = Color(0xFFEFF1F1)
internal val light_inverseSurface = Color(0xFF2D3131)
internal val light_inversePrimary = Color(0xFF3DDAE7)
internal val light_shadow = Color(0xFF000000)
internal val light_surfaceTint = Color(0xFF006970)
internal val light_outlineVariant = Color(0xFFBEC8C9)
internal val light_scrim = Color(0xFF000000)

@SuppressLint("ComposeCompositionLocalUsage")
internal val LocalAppColors = staticCompositionLocalOf { LightColors }
