#!/bin/bash

commit_msg=$(cat "${1:?Missing .git/COMMIT_EDITMSG}")
options="(build|ci|docs|feat|fix|perf|refactor|style|test|chore|revert)"
pattern="^${options}(\(.+\))?:[[:space:]]+.*$"

exit_status=-1
if [[ ${commit_msg} =~ $pattern ]]; then
        exit_status=$?
    else
        exit_status=$?
        echo "${red}Commit message must follow Conventional Commits pattern https://www.conventionalcommits.org/en/v1.0.0/${normal}"
        echo "${red}options are ${options}${normal}"
fi

exit ${exit_status}
