#!/bin/bash

check_branch_name() {
    echo "> Checking branch name...."
    branch_types="(feature|bugfix|hotfix|refactor|experimental)"
    branch_name_pattern="^${branch_types}\/[A-Z]+-[0-9]+-[A-Za-z]+([-][A-Za-z0-9]+)*$|^(chore\/renovate+-[A-Za-z0-9]+)"

    branch_name=$(echo $(git rev-parse --abbrev-ref HEAD))

    if [[ ! ${branch_name} =~ $branch_name_pattern ]]; then
        echo "${red}> Invalid branch name: ${branch_name}${normal}"
        echo "  - Branch names must be in the format of: <type>/<ticket-number>-<short-description>"
        echo "    - Valid branch types are: ${branch_types}."
        echo "    - The ticket number should be a capital word followed by a hyphen and one or more digits (e.g. ABC-123)."
        echo "    - The short description should be a lowercase word or phrase with hyphens between words."
        echo "  - Renovate branch names should be in the format: chore/renovate-<short-description>"
        exit 1
    fi
}

echo "> Running pre-push hooks..."

check_branch_name

echo "> ${green}Pre-push checks successful${normal}"

exit 0
